import Footer from '@/components/footer'
import Header from '@/components/headers'
import '@/styles/globals.scss'
import type { AppProps } from 'next/app'
import "@/styles/layout.scss"
import Head from 'next/head'
import Script from "next/script"

import {useRouter} from "next/router"
export default function App({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Huge Digital Clock</title>
      <Script strategy="afterInteractive" src="https://www.googletagmanager.com/gtag/js?id=G-YJDS2446N9" />
      <Script
        id="google-analytics"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html:`
          window.dataLayer = window.dataLayer || [];
          function gtag() { dataLayer.push(arguments); }
          gtag('js', new Date());
          gtag('config', 'G-YJDS2446N9');
          `
        }}/>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="/favicon.ico" />
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet"></link>
    </Head>
    <Header />
    <Component {...pageProps} />
    <Footer />
  </>

}
